name: music_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  audio_video_progress_bar: ^0.11.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  get: 4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.7.0
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  on_audio_query: ^2.6.1
  path_provider: ^2.0.11
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_black.png
    - assets/images/icon_white.png
